[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21
    libsodium
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUHAL_LOG_COLORS=1

[env:esp32-s3-tls]
extends = env:esp32-s3
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DMQTT_TLS_ENABLED

[env:esp32-s3-test]
extends = env:esp32-s3
test_framework = unity
test_filter = test_ota
